In [8]:
import pandas as pd #El manejo de archivos csv
import pyodbc #Para la conexion con SQL SERVER
import numpy as np #Manejos numericos
import string #En caso de necesitar manejo de strings

In [9]:
csv_file = 'POS_CASH_balance.csv'
df = pd.read_csv(csv_file,decimal=',')

In [10]:
df = df.where(pd.notnull(df), None)

In [21]:
# Configura la cadena de conexión
server = 'DESKTOP-5GQ42K8'
database = 'ProyectoBases'
username = 'sa'
password = '12345'

# Crea la cadena de conexión
conn_str = f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}'

# Establece la conexión
conn = pyodbc.connect(conn_str)
cursor = conn.cursor() #Abre un cursor

CERRAR CONEXION

In [20]:
conn.commit()
# Cerrar el cursor
cursor.close()

# Cerrar la conexión
conn.close()


*APPLICATION TRAIN*

Creación de tablas

In [22]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE APPLICATION_TRAIN(
    # SK_ID_CURR INT,
    # TARGET BIT,
    # NAME_CONTRACT_TYPE NVARCHAR(50),
    # DAYS_REGISTRATION INT, 
    # DAYS_PUBLISH INT, 
    # WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
    # HOUR_APPR_PROCESS_START	INT,
    # AMT_INCOME_TOTAL FLOAT,
    # AMT_CREDIT FLOAT,
    # AMT_ANNUITY	FLOAT,
    # AMT_GOODS_PRICE	FLOAT,
    # ID_CURTOMER_APPLICATION	INT,
    # ID_REQUEST_APLICATIONS INT,
    # ID_BUILD_CUSTOMER_AVG INT,
    # ID_BUILD_CUSTOMER_MODE INT,
    # ID_BUILD_CUSTOMER_MEDI INT,
    # ID_EXT_SOURCE INT,
    # ID_DOCUMENT_APLICATION INT,
#     FOREIGN KEY (ID_CURTOMER_APPLICATION) REFERENCES CUSTOMER_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_REQUEST_APLICATIONS) REFERENCES AMT_REQUEST_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_BUILD_CUSTOMER_AVG) REFERENCES BUILD_COSTUMER_AVG_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_BUILD_CUSTOMER_MODE) REFERENCES BUILD_COSTUMER_MODE_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_BUILD_CUSTOMER_MEDI) REFERENCES BUILD_COSTUMER_MEDI_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_EXT_SOURCE) REFERENCES EXT_SOURCES_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_DOCUMENT_APLICATION) REFERENCES DOCUMENT_APLICATION_TRAIN (ID),
#     CONSTRAINT pk_APLICATION_TRAIN PRIMARY KEY(SK_ID_CURR)

# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [15]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE CUSTOMER_APPLICATION_TRAIN(
    # ID INT,
    # CODE_GENDER char(1),
    # CNT_CHILDREN TINYINT,
    # NAME_TYPE_SUITE	NVARCHAR(50),
    # NAME_INCOME_TYPE NVARCHAR(50),
    # NAME_EDUCATION_TYPE	NVARCHAR(50),
    # NAME_FAMILY_STATUS NVARCHAR(50),
    # NAME_HOUSING_TYPE NVARCHAR(50),
    # DAYS_BIRTH	INT,
    # DAYS_EMPLOYED INT,
    # OCCUPATION_TYPE	NVARCHAR(50),
    # CNT_FAM_MEMBERS	INT,
    # ORGANIZATION_TYPE NVARCHAR(50),
    # ID_PERSONAL_CONTACT	INT,
    # ID_PERSONAL_PROPERTIES INT,
    # ID_REGION_QUALIFICATION_CUSTOMERS INT,
    # ID_CUSTUMER_CUSTOMER INT,
#     FOREIGN KEY (ID_PERSONAL_CONTACT) REFERENCES CONTACT_CUSTOMER_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_PERSONAL_PROPERTIES) REFERENCES PROPERTIES_CUSTOMERS_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_REGION_QUALIFICATION_CUSTOMERS) REFERENCES REGION_QUALIFICATION_APPLICATION_TRAIN (ID),
#     FOREIGN KEY (ID_CUSTUMER_CUSTOMER) REFERENCES CUSTUMER_CUSTOMER_APPLICATION_TRAIN (ID),
#     CONSTRAINT pk_CUSTOMER_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [6]:
#Listoooo
# create_table_query = '''
# CREATE TABLE PROPERTIES_CUSTOMERS_APPLICATION_TRAIN (
#     ID INT,
#     FLAG_OWN_CAR CHAR(1),
#     FLAG_OWN_REALTY CHAR(1),
#     OWN_CAR_AGE INT
#     CONSTRAINT pk_PROPERTIES_CUSTOMERS_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [53]:
# lISTOOO
# create_table_query = '''
# CREATE TABLE CONTACT_CUSTOMER_APPLICATION_TRAIN(
#     ID INT,
#     FLAG_MOBIL BIT,
#     FlAG_EMP_PHONE BIT,
#     FLAG_CONT_MOBILE BIT,
#     FLAG_PHONE BIT,
#     FLAG_EMAIL BIT,
#     DAYS_LAST_PHONE_CHANGE INT,
#     CONSTRAINT pk_CONTACT_CUSTOMER_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [194]:
#Listoooo
# create_table_query = '''
# CREATE TABLE AMT_REQUEST_APPLICATION_TRAIN(
#     ID INT,
#     AMT_REQ_CREDIT_BUREAU_HOUR FLOAT,
#     AMT_REQ_CREDIT_BUREAU_DAY FLOAT,
#     AMT_REQ_CREDIT_BUREAU_WEEK FLOAT,
#     AMT_REQ_CREDIT_BUREAU_MON FLOAT,
#     AMT_REQ_CREDIT_BUREAU_QRT FLOAT,
#     AMT_REQ_CREDIT_BUREAU_YEAR FLOAT,
#     CONSTRAINT pk_AMT_REQUEST_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [26]:
#LISTOOO 
# create_table_query = '''
# CREATE TABLE REGION_QUALIFICATION_APPLICATION_TRAIN(
#     ID INT,
#     REGION_POPULATION_RELATIVE FLOAT,
#     REGION_RATING_CLIENT INT,
#     REGION_RATING_CLIENT_W_CITY INT,
#     REG_REGION_NOT_LIVE_REGION INT,
#     REG_REGION_NOT_WORK_REGION INT, 
#     LIVE_REGION_NOT_WORK_REGION INT,
#     REG_CITY_NOT_LIVE_CITY INT,
#     REG_CITY_NOT_WORK_CITY INT,
#     LIVE_CITY_NOT_WORK_CITY INT,
#     CONSTRAINT pk_REGION_QUALIFICATION_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [10]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE BUILD_COSTUMER_AVG_APPLICATION_TRAIN(
#     ID INT,
#     APARTMENTS_AVG FLOAT,
#     BASEMENTAREA_AVG FLOAT,
#     YEARS_BEGINEXPLUATATION_AVG FLOAT,
#     YEARS_BUILD_AVG FLOAT, 
#     COMMONAREA_AVG FLOAT,
#     ELEVATORS_AVG FLOAT,
#     ENTRANCES_AVG FLOAT, 
#     FLOORSMAX_AVG FLOAT,
#     FLOORSMIN_AVG FLOAT,
#     LANDAREA_AVG FLOAT,
#     LIVINGAPARTMENTS_AVG FLOAT,
#     LIVINGAREA_AVG FLOAT,
#     NONLIVINGAPARTMENTS_AVG FLOAT,
#     NONLIVINGAREA_AVG FLOAT, 
#     CONSTRAINT pk_BUILD_COSTUMER_AVG_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [64]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE BUILD_COSTUMER_MODE_APPLICATION_TRAIN(
#     ID INT,
#     APARTMENTS_MODE FLOAT,
#     BASEMENTAREA_MODE FLOAT,
#     YEARS_BEGINEXPLUATATION_MODE FLOAT,
#     YEARS_BUILD_MODE FLOAT,
#     COMMONAREA_MODE FLOAT,
#     ELEVATORS_MODE FLOAT,
#     ENTRANCES_MODE FLOAT,
#     FLOORSMAX_MODE FLOAT,
#     FLOORSMIN_MODE FLOAT,
#     LANDAREA_MODE FLOAT,
#     LIVINGAPARTMENTS_MODE FLOAT,
#     LIVINGAREA_MODE FLOAT,
#     NONLIVINGAPARTMENTS_MODE FLOAT,
#     NONLIVINGAREA_MODE FLOAT,
#     FONDKAPREMONT_MODE NVARCHAR(50),
#     HOUSETYPE_MODE NVARCHAR(50),
#     TOTALAREA_MODE FLOAT,   
#     WALLSMATERIAL_MODE NVARCHAR(50),
#     EMERGENCYSTATE_MODE NVARCHAR(50),
#     CONSTRAINT pk_BUILD_COSTUMER_MODE_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [18]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE BUILD_COSTUMER_MEDI_APPLICATION_TRAIN(
#     ID INT,
#     APARTMENTS_MEDI	FLOAT,
#     BASEMENTAREA_MEDI FLOAT,
#     YEARS_BEGINEXPLUATATION_MEDI FLOAT,
#     YEARS_BUILD_MEDI FLOAT,
#     COMMONAREA_MEDI	FLOAT,
#     ELEVATORS_MEDI FLOAT,
#     ENTRANCES_MEDI FLOAT,
#     FLOORSMAX_MEDI FLOAT,
#     FLOORSMIN_MEDI FLOAT,
#     LANDAREA_MEDI FLOAT,
#     LIVINGAPARTMENTS_MEDI FLOAT,
#     LIVINGAREA_MEDI	FLOAT,
#     NONLIVINGAPARTMENTS_MEDI FLOAT,
#     NONLIVINGAREA_MEDI FLOAT,
#     CONSTRAINT pk_BUILD_COSTUMER_MEDI_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [76]:
#listoo
# create_table_query = '''
# CREATE TABLE CUSTUMER_CUSTOMER_APPLICATION_TRAIN(
#     ID INT,
#     OBS_30_CNT_SOCIAL_CIRCLE FLOAT,
#     DEF_30_CNT_SOCIAL_CIRCLE FLOAT,
#     OBS_60_CNT_SOCIAL_CIRCLE FLOAT,
#     DEF_60_CNT_SOCIAL_CIRCLE FLOAT,
#     CONSTRAINT pk_CUSTUMER_CUSTOMER_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [118]:
# LISTOO
# create_table_query = '''
# CREATE TABLE DOCUMENT_APLICATION_TRAIN(
#     ID INT,
#     FLAG_DOCUMENT_2	INT,
#     FLAG_DOCUMENT_3	INT,
#     FLAG_DOCUMENT_4	INT,
#     FLAG_DOCUMENT_5	INT,
#     FLAG_DOCUMENT_6	INT,
#     FLAG_DOCUMENT_7	INT,
#     FLAG_DOCUMENT_8	INT,
#     FLAG_DOCUMENT_9	INT,
#     FLAG_DOCUMENT_10 INT,
#     FLAG_DOCUMENT_11 INT,
#     FLAG_DOCUMENT_12 INT,
#     FLAG_DOCUMENT_13 INT,
#     FLAG_DOCUMENT_14 INT,
#     FLAG_DOCUMENT_15 INT,
#     FLAG_DOCUMENT_16 INT,
#     FLAG_DOCUMENT_17 INT,
#     FLAG_DOCUMENT_18 INT,
#     FLAG_DOCUMENT_19 INT,
#     FLAG_DOCUMENT_20 INT,
#     FLAG_DOCUMENT_21 INT,
#     CONSTRAINT pk_DOCUMENT_APLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [131]:
# LISTOOO
# create_table_query = '''
# CREATE TABLE EXT_SOURCES_APPLICATION_TRAIN(
#     ID INT,
#     EXT_SOURCE_1 FLOAT,
#     EXT_SOURCE_2 FLOAT,
#     EXT_SOURCE_3 FLOAT,
#     CONSTRAINT pk_EXT_SOURCES_APPLICATION_TRAIN PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

Insertar Datos

In [23]:
#LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     sk_id_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0
#     target = int(row['TARGET']) if pd.notnull(row['TARGET']) else 0
#     name_contract_type = str(row['NAME_CONTRACT_TYPE']) if pd.notnull(row['NAME_CONTRACT_TYPE']) else None
#     days_registration = float(row['DAYS_REGISTRATION']) if pd.notnull(row['DAYS_REGISTRATION']) else 0.0
#     days_publish = int(row['DAYS_ID_PUBLISH']) if pd.notnull(row['DAYS_ID_PUBLISH']) else 0
#     weekday_appr_process_start = str(row['WEEKDAY_APPR_PROCESS_START']) if pd.notnull(row['WEEKDAY_APPR_PROCESS_START']) else None
#     hour_appr_process_start = int(row['HOUR_APPR_PROCESS_START']) if pd.notnull(row['HOUR_APPR_PROCESS_START']) else 0
#     amt_income_total = float(row['AMT_INCOME_TOTAL']) if pd.notnull(row['AMT_INCOME_TOTAL']) and isinstance(row['AMT_INCOME_TOTAL'], (int, float)) else 0.0
#     amt_credit = float(row['AMT_CREDIT']) if pd.notnull(row['AMT_CREDIT']) else 0.0
#     amt_annuity = float(row['AMT_ANNUITY']) if pd.notnull(row['AMT_ANNUITY']) else 0.0
#     amt_goods_price = float(row['AMT_GOODS_PRICE']) if pd.notnull(row['AMT_GOODS_PRICE']) else 0.0
#     id_customer_application = int(row['ID_CURTOMER_APPLICATION']) if pd.notnull(row['ID_CURTOMER_APPLICATION']) else 0
#     id_request_application = int(row['ID_REQUEST_APLICATIONS']) if pd.notnull(row['ID_REQUEST_APLICATIONS']) else 0
#     id_build_customer_avg = int(row['ID_BUILD_CUSTOMER_AVG']) if pd.notnull(row['ID_BUILD_CUSTOMER_AVG']) else 0
#     id_build_customer_mode = int(row['ID_BUILD_CUSTOMER_MODE']) if pd.notnull(row['ID_BUILD_CUSTOMER_MODE']) else 0
#     id_build_customer_medi = int(row['ID_BUILD_CUSTOMER_MEDI']) if pd.notnull(row['ID_BUILD_CUSTOMER_MEDI']) else 0
#     id_ext_source = int(row['ID_EXT_SOURCE']) if pd.notnull(row['ID_EXT_SOURCE']) else 0
#     id_document_application = int(row['ID_DOCUMENT_APLICATION']) if pd.notnull(row['ID_DOCUMENT_APLICATION']) else 0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO APPLICATION_TRAIN (SK_ID_CURR, TARGET, NAME_CONTRACT_TYPE, DAYS_REGISTRATION, DAYS_PUBLISH, WEEKDAY_APPR_PROCESS_START, 
#     HOUR_APPR_PROCESS_START, AMT_INCOME_TOTAL, AMT_CREDIT, AMT_ANNUITY, AMT_GOODS_PRICE, ID_CURTOMER_APPLICATION, ID_REQUEST_APLICATIONS, 
#     ID_BUILD_CUSTOMER_AVG, ID_BUILD_CUSTOMER_MODE, ID_BUILD_CUSTOMER_MEDI, ID_EXT_SOURCE, ID_DOCUMENT_APLICATION)
#     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (sk_id_curr, target, name_contract_type, days_registration, days_publish, weekday_appr_process_start,
#     hour_appr_process_start, amt_income_total, amt_credit, amt_annuity, amt_goods_price, id_customer_application, id_request_application,
#     id_build_customer_avg, id_build_customer_mode,id_build_customer_medi, id_ext_source, id_document_application))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [17]:
#LISTOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo adecuado
#     id_value = int(row['ID']) if pd.notnull(row['ID']) else 0
#     code_gender = str(row['CODE_GENDER']) if pd.notnull(row['CODE_GENDER']) else None
#     cnt_children = int(row['CNT_CHILDREN']) if pd.notnull(row['CNT_CHILDREN']) else 0
#     name_type_suite = str(row['NAME_TYPE_SUITE']) if pd.notnull(row['NAME_TYPE_SUITE']) else None
#     name_income_type = str(row['NAME_INCOME_TYPE']) if pd.notnull(row['NAME_INCOME_TYPE']) else None
#     name_education_type = str(row['NAME_EDUCATION_TYPE']) if pd.notnull(row['NAME_EDUCATION_TYPE']) else None
#     name_family_status = str(row['NAME_FAMILY_STATUS']) if pd.notnull(row['NAME_FAMILY_STATUS']) else None
#     name_housing_type = str(row['NAME_HOUSING_TYPE']) if pd.notnull(row['NAME_HOUSING_TYPE']) else None
#     days_birth = int(row['DAYS_BIRTH']) if pd.notnull(row['DAYS_BIRTH']) else 0
#     days_employed = int(row['DAYS_EMPLOYED']) if pd.notnull(row['DAYS_EMPLOYED']) else 0
#     occupation_type = str(row['OCCUPATION_TYPE']) if pd.notnull(row['OCCUPATION_TYPE']) else None
#     cnt_fam_members = float(row['CNT_FAM_MEMBERS']) if pd.notnull(row['CNT_FAM_MEMBERS']) else 0.0
#     organization_type = str(row['ORGANIZATION_TYPE']) if pd.notnull(row['ORGANIZATION_TYPE']) else None
#     id_customer_contact = int(row['ID_CUSTOMER_CONTACT']) if pd.notnull(row['ID_CUSTOMER_CONTACT']) else 0
#     id_customer_properties = int(row['ID_CUSTOMER_PROPERTIES']) if pd.notnull(row['ID_CUSTOMER_PROPERTIES']) else 0
#     id_region_qualification_customers = int(row['ID_REGION_QUALIFICATION_CUSTOMERS']) if pd.notnull(row['ID_REGION_QUALIFICATION_CUSTOMERS']) else 0
#     id_custumer_customer = int(row['ID_CUSTUMER_CUSTOMER']) if pd.notnull(row['ID_CUSTUMER_CUSTOMER'])  else 0
    
#     if code_gender is not None and len(code_gender) != 1:
#         code_gender = 'N'
#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO CUSTOMER_APPLICATION_TRAIN (ID, CODE_GENDER, CNT_CHILDREN, NAME_TYPE_SUITE, NAME_INCOME_TYPE, NAME_EDUCATION_TYPE, 
#     NAME_FAMILY_STATUS, NAME_HOUSING_TYPE, DAYS_BIRTH, DAYS_EMPLOYED, OCCUPATION_TYPE, CNT_FAM_MEMBERS, ORGANIZATION_TYPE, ID_PERSONAL_CONTACT, 
#     ID_PERSONAL_PROPERTIES, ID_REGION_QUALIFICATION_CUSTOMERS, ID_CUSTUMER_CUSTOMER)
#     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, id_value, code_gender, cnt_children, name_type_suite, name_income_type, name_education_type,
#     name_family_status, name_housing_type, days_birth, days_employed, occupation_type, cnt_fam_members, organization_type,
#     id_customer_contact, id_customer_properties, id_region_qualification_customers, id_custumer_customer)

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [7]:
#listoooo
# for index, row in df.iterrows():
#     # Verificar si OWN_CAR_AGE no es nulo y es numérico
#     if row['OWN_CAR_AGE'] is not None and str(row['OWN_CAR_AGE']).isnumeric():
#         # Convertir OWN_CAR_AGE a entero si no es nulo y es numérico
#         own_car_age = int(row['OWN_CAR_AGE'])
#     else:
#         # Establecer un valor predeterminado o manejar el caso de ser nulo o no numérico
#         own_car_age = 0  # Cambia esto por el valor predeterminado que desees

#     insert_query = "INSERT INTO PROPERTIES_CUSTOMERS_APPLICATION_TRAIN (ID, FLAG_OWN_CAR, FLAG_OWN_REALTY, OWN_CAR_AGE) VALUES (?, ?, ?, ?)"
#     cursor.execute(insert_query, row['ID'], row['FLAG_OWN_CAR'], row['FLAG_OWN_REALTY'], own_car_age)
    
# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [55]:
# LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a los tipos correctos
#     id_value = int(row['ID']) if isinstance(row['ID'], (int, float)) else 0
#     flag_mobil = int(row['FLAG_MOBIL']) if isinstance(row['FLAG_MOBIL'], (int, float)) and row['FLAG_MOBIL'] in [0, 1] else 0
#     flag_emp_phone = int(row['FLAG_EMP_PHONE']) if isinstance(row['FLAG_EMP_PHONE'], (int, float)) and row['FLAG_EMP_PHONE'] in [0, 1] else 0
#     flag_cont_mobile = int(row['FLAG_CONT_MOBILE']) if isinstance(row['FLAG_CONT_MOBILE'], (int, float)) and row['FLAG_CONT_MOBILE'] in [0, 1] else 0
#     flag_phone = int(row['FLAG_PHONE']) if isinstance(row['FLAG_PHONE'], (int, float)) and row['FLAG_PHONE'] in [0, 1] else 0
#     flag_email = int(row['FLAG_EMAIL']) if isinstance(row['FLAG_EMAIL'], (int, float)) and row['FLAG_EMAIL'] in [0, 1] else 0

#     # Handle DAYS_LAST_PHONE_CHANGE, set to 0 if not a number
#     try:
#         days_last_phone_change = float(row['DAYS_LAST_PHONE_CHANGE'])
#     except (ValueError, TypeError):
#         days_last_phone_change = 0.0

#     insert_query = '''
#     INSERT INTO CONTACT_CUSTOMER_APPLICATION_TRAIN ( ID, FLAG_MOBIL, FlAG_EMP_PHONE, FLAG_CONT_MOBILE, FLAG_PHONE, FLAG_EMAIL, DAYS_LAST_PHONE_CHANGE) VALUES (?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, id_value, flag_mobil, flag_emp_phone, flag_cont_mobile, flag_phone, flag_email, days_last_phone_change)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [195]:
#Listoooo
# import numpy as np  # Añade esta importación al comienzo del código si aún no está importada

# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     id_value = int(row['ID']) if isinstance(row['ID'], (int, float)) else 0
#     amt_req_credit_bureau_hour = float(row['AMT_REQ_CREDIT_BUREAU_HOUR']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_HOUR']) else 0
#     amt_req_credit_bureau_day = float(row['AMT_REQ_CREDIT_BUREAU_DAY']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_DAY']) else 0
#     amt_req_credit_bureau_week = float(row['AMT_REQ_CREDIT_BUREAU_WEEK']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_WEEK']) else 0
#     amt_req_credit_bureau_mon = float(row['AMT_REQ_CREDIT_BUREAU_MON']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_MON']) else 0
#     amt_req_credit_bureau_qrt = float(row['AMT_REQ_CREDIT_BUREAU_QRT']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_QRT']) else 0
#     amt_req_credit_bureau_year = float(row['AMT_REQ_CREDIT_BUREAU_YEAR']) if pd.notna(row['AMT_REQ_CREDIT_BUREAU_YEAR']) else 0

#     insert_query = '''
#     INSERT INTO AMT_REQUEST_APPLICATION_TRAIN(ID, AMT_REQ_CREDIT_BUREAU_HOUR, AMT_REQ_CREDIT_BUREAU_DAY, AMT_REQ_CREDIT_BUREAU_WEEK, 
#         AMT_REQ_CREDIT_BUREAU_MON, AMT_REQ_CREDIT_BUREAU_QRT, AMT_REQ_CREDIT_BUREAU_YEAR) VALUES (?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, id_value, amt_req_credit_bureau_hour, amt_req_credit_bureau_day, amt_req_credit_bureau_week, 
#                    amt_req_credit_bureau_mon, amt_req_credit_bureau_qrt, amt_req_credit_bureau_year)

# conn.commit()
# # Cerrar el cursor
# cursor.close()
# # Cerrar la conexión
# conn.close()

In [27]:
#LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo INT
#     region_population_relative = float(row['REGION_POPULATION_RELATIVE']) 
#     region_rating_client = int(row['REGION_RATING_CLIENT']) if isinstance(row['REGION_RATING_CLIENT'], (int)) else 0
#     region_rating_client_w_city = int(row['REGION_RATING_CLIENT_W_CITY']) if isinstance(row['REGION_RATING_CLIENT_W_CITY'], (int)) else 0
#     reg_region_not_live_region = int(row['REG_REGION_NOT_LIVE_REGION']) if isinstance(row['REG_REGION_NOT_LIVE_REGION'], (int)) else 0
#     reg_region_not_work_region = int(row['REG_REGION_NOT_WORK_REGION']) if isinstance(row['REG_REGION_NOT_WORK_REGION'], (int)) else 0
#     live_region_not_work_region = int(row['LIVE_REGION_NOT_WORK_REGION']) if isinstance(row['LIVE_REGION_NOT_WORK_REGION'], (int)) else 0
#     reg_city_not_live_city = int(row['REG_CITY_NOT_LIVE_CITY']) if isinstance(row['REG_CITY_NOT_LIVE_CITY'], (int)) else 0
#     reg_city_not_work_city = int(row['REG_CITY_NOT_WORK_CITY']) if isinstance(row['REG_CITY_NOT_WORK_CITY'], (int)) else 0
#     live_city_not_work_city = int(row['LIVE_CITY_NOT_WORK_CITY']) if isinstance(row['LIVE_CITY_NOT_WORK_CITY'], (int)) else 0

#     insert_query = '''
#     INSERT INTO REGION_QUALIFICATION_APPLICATION_TRAIN (ID, REGION_POPULATION_RELATIVE, REGION_RATING_CLIENT, REGION_RATING_CLIENT_W_CITY, 
#         REG_REGION_NOT_LIVE_REGION, REG_REGION_NOT_WORK_REGION, LIVE_REGION_NOT_WORK_REGION, REG_CITY_NOT_LIVE_CITY, REG_CITY_NOT_WORK_CITY, 
#         LIVE_CITY_NOT_WORK_CITY) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, row['ID'], region_population_relative, region_rating_client, region_rating_client_w_city, reg_region_not_live_region, 
#                    reg_region_not_work_region, live_region_not_work_region, reg_city_not_live_city, reg_city_not_work_city, live_city_not_work_city)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [12]:
#LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT
    
#     apartments_avg = float(row['APARTMENTS_AVG']) if pd.notna(row['APARTMENTS_AVG']) else 0.0
#     basementarea_avg = float(row['BASEMENTAREA_AVG']) if pd.notna(row['BASEMENTAREA_AVG']) else 0.0
#     years_beginexpluatation_avg = float(row['YEARS_BEGINEXPLUATATION_AVG']) if pd.notna(row['YEARS_BEGINEXPLUATATION_AVG']) else 0.0
#     years_build_avg = float(row['YEARS_BUILD_AVG']) if pd.notna(row['YEARS_BUILD_AVG']) else 0.0
#     commonarea_avg = float(row['COMMONAREA_AVG']) if pd.notna(row['COMMONAREA_AVG']) else 0.0
#     elevators_avg = float(row['ELEVATORS_AVG']) if pd.notna(row['ELEVATORS_AVG']) else 0.0
#     entrances_avg = float(row['ENTRANCES_AVG']) if pd.notna(row['ENTRANCES_AVG']) else 0.0
#     floorsmax_avg = float(row['FLOORSMAX_AVG']) if pd.notna(row['FLOORSMAX_AVG']) else 0.0
#     floorsmin_avg = float(row['FLOORSMIN_AVG']) if pd.notna(row['FLOORSMIN_AVG']) else 0.0
#     landarea_avg = float(row['LANDAREA_AVG']) if pd.notna(row['LANDAREA_AVG']) else 0.0
#     livingaparments_avg = float(row['LIVINGAPARTMENTS_AVG']) if pd.notna(row['LIVINGAPARTMENTS_AVG']) else 0.0
#     livingarea_avg = float(row['LIVINGAREA_AVG']) if pd.notna(row['LIVINGAREA_AVG']) else 0.0
#     nonlivingapartments_avg = float(row['NONLIVINGAPARTMENTS_AVG']) if pd.notna(row['NONLIVINGAPARTMENTS_AVG']) else 0.0
#     nonlivingarea_avg = float(row['NONLIVINGAREA_AVG']) if pd.notna(row['NONLIVINGAREA_AVG']) else 0.0
    


#     insert_query = '''
#     INSERT INTO BUILD_COSTUMER_AVG_APPLICATION_TRAIN (ID, APARTMENTS_AVG, BASEMENTAREA_AVG, YEARS_BEGINEXPLUATATION_AVG, YEARS_BUILD_AVG, 
#         COMMONAREA_AVG, ELEVATORS_AVG, ENTRANCES_AVG, FLOORSMAX_AVG, FLOORSMIN_AVG, LANDAREA_AVG, LIVINGAPARTMENTS_AVG, LIVINGAREA_AVG, 
#         NONLIVINGAPARTMENTS_AVG, NONLIVINGAREA_AVG) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, row['ID'], apartments_avg, basementarea_avg, years_beginexpluatation_avg, years_build_avg, commonarea_avg, 
#                    elevators_avg, entrances_avg, floorsmax_avg, floorsmin_avg, landarea_avg, livingaparments_avg, livingarea_avg, 
#                    nonlivingapartments_avg, nonlivingarea_avg)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [65]:
#lISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o NULL
#     apartments_mode = float(row['APARTMENTS_MODE'])  if pd.notna(row['APARTMENTS_MODE']) else 0.0
#     basementarea_mode = float(row['BASEMENTAREA_MODE'])  if pd.notna(row['BASEMENTAREA_MODE']) else 0.0
#     years_beginexpluatation_mode = float(row['YEARS_BEGINEXPLUATATION_MODE'])  if pd.notna(row['YEARS_BEGINEXPLUATATION_MODE']) else 0.0
#     years_build_mode = float(row['YEARS_BUILD_MODE'])  if pd.notna(row['YEARS_BUILD_MODE']) else 0.0
#     commonarea_mode = float(row['COMMONAREA_MODE'])  if pd.notna(row['COMMONAREA_MODE']) else 0.0
#     elevators_mode = float(row['ELEVATORS_MODE'])  if pd.notna(row['ELEVATORS_MODE']) else 0.0
#     entrances_mode = float(row['ENTRANCES_MODE'])  if pd.notna(row['ENTRANCES_MODE']) else 0.0
#     floorsmax_mode = float(row['FLOORSMAX_MODE'])  if pd.notna(row['FLOORSMAX_MODE']) else 0.0
#     floorsmin_mode = float(row['FLOORSMIN_MODE'])  if pd.notna(row['FLOORSMIN_MODE']) else 0.0
#     landarea_mode = float(row['LANDAREA_MODE'])  if pd.notna(row['LANDAREA_MODE']) else 0.0
#     livingapartments_mode = float(row['LIVINGAPARTMENTS_MODE'])  if pd.notna(row['LIVINGAPARTMENTS_MODE']) else 0.0
#     livingarea_mode = float(row['LIVINGAREA_MODE'])  if pd.notna(row['LIVINGAREA_MODE']) else 0.0
#     nonlivingapartments_mode = float(row['NONLIVINGAPARTMENTS_MODE'])  if pd.notna(row['NONLIVINGAPARTMENTS_MODE']) else 0.0
#     nonlivingarea_mode = float(row['NONLIVINGAREA_MODE'])  if pd.notna(row['NONLIVINGAREA_MODE']) else 0.0
#     fondkapremont_mode = str(row['FONDKAPREMONT_MODE'])  if pd.notna(row['FONDKAPREMONT_MODE']) else None
#     housetype_mode = str(row['HOUSETYPE_MODE'])  if pd.notna(row['HOUSETYPE_MODE']) else None
#     totalarea_mode = float(row['TOTALAREA_MODE'])  if pd.notna(row['TOTALAREA_MODE']) else 0.0
#     wallsmaterial_mode = str(row['WALLSMATERIAL_MODE'])  if pd.notna(row['WALLSMATERIAL_MODE']) else None
#     emergencystate_mode = str(row['EMERGENCYSTATE_MODE'])  if pd.notna(row['EMERGENCYSTATE_MODE']) else None

#     insert_query = '''
#     INSERT INTO BUILD_COSTUMER_MODE_APPLICATION_TRAIN (ID, APARTMENTS_MODE, BASEMENTAREA_MODE, YEARS_BEGINEXPLUATATION_MODE, YEARS_BUILD_MODE, 
#         COMMONAREA_MODE, ELEVATORS_MODE, ENTRANCES_MODE, FLOORSMAX_MODE, FLOORSMIN_MODE, LANDAREA_MODE, LIVINGAPARTMENTS_MODE, LIVINGAREA_MODE, 
#         NONLIVINGAPARTMENTS_MODE, NONLIVINGAREA_MODE, FONDKAPREMONT_MODE, HOUSETYPE_MODE, TOTALAREA_MODE, WALLSMATERIAL_MODE, EMERGENCYSTATE_MODE
#     ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, row['ID'], apartments_mode, basementarea_mode, years_beginexpluatation_mode, years_build_mode, commonarea_mode, 
#                    elevators_mode, entrances_mode, floorsmax_mode, floorsmin_mode, landarea_mode, livingapartments_mode, livingarea_mode, 
#                    nonlivingapartments_mode, nonlivingarea_mode, fondkapremont_mode, housetype_mode, totalarea_mode, wallsmaterial_mode, 
#                    emergencystate_mode)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [19]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     apartments_medi = float(row['APARTMENTS_MEDI']) if pd.notnull(row['APARTMENTS_MEDI']) else 0.0
#     basementarea_medi = float(row['BASEMENTAREA_MEDI']) if pd.notnull(row['BASEMENTAREA_MEDI']) else 0.0
#     years_beginexpluatation_medi = float(row['YEARS_BEGINEXPLUATATION_MEDI']) if pd.notnull(row['YEARS_BEGINEXPLUATATION_MEDI']) else 0.0
#     years_build_medi = float(row['YEARS_BUILD_MEDI']) if pd.notnull(row['YEARS_BUILD_MEDI']) else 0.0
#     commonarea_medi = float(row['COMMONAREA_MEDI']) if pd.notnull(row['COMMONAREA_MEDI']) else 0.0
#     elevators_medi = float(row['ELEVATORS_MEDI']) if pd.notnull(row['ELEVATORS_MEDI']) else 0.0
#     entrances_medi = float(row['ENTRANCES_MEDI']) if pd.notnull(row['ENTRANCES_MEDI']) else 0.0
#     floorsmax_medi = float(row['FLOORSMAX_MEDI']) if pd.notnull(row['FLOORSMAX_MEDI']) else 0.0
#     floorsmin_medi = float(row['FLOORSMIN_MEDI']) if pd.notnull(row['FLOORSMIN_MEDI']) else 0.0
#     landarea_medi = float(row['LANDAREA_MEDI']) if pd.notnull(row['LANDAREA_MEDI']) else 0.0
#     livingapartments_medi = float(row['LIVINGAPARTMENTS_MEDI']) if pd.notnull(row['LIVINGAPARTMENTS_MEDI']) else 0.0
#     livingarea_medi = float(row['LIVINGAREA_MEDI']) if pd.notnull(row['LIVINGAREA_MEDI']) else 0.0
#     nonlivingapartments_medi = float(row['NONLIVINGAPARTMENTS_MEDI']) if pd.notnull(row['NONLIVINGAPARTMENTS_MEDI']) else 0.0
#     nonlivingarea_medi = float(row['NONLIVINGAREA_MEDI']) if pd.notnull(row['NONLIVINGAREA_MEDI']) else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO BUILD_COSTUMER_MEDI_APPLICATION_TRAIN (ID, APARTMENTS_MEDI, BASEMENTAREA_MEDI, YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI, 
#     COMMONAREA_MEDI, ELEVATORS_MEDI, ENTRANCES_MEDI, FLOORSMAX_MEDI, FLOORSMIN_MEDI, LANDAREA_MEDI, LIVINGAPARTMENTS_MEDI, LIVINGAREA_MEDI, 
#     NONLIVINGAPARTMENTS_MEDI, NONLIVINGAREA_MEDI) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, row['ID'], apartments_medi, basementarea_medi, years_beginexpluatation_medi, years_build_medi, commonarea_medi, 
#                     elevators_medi, entrances_medi, floorsmax_medi, floorsmin_medi, landarea_medi, livingapartments_medi, livingarea_medi, 
#                     nonlivingapartments_medi, nonlivingarea_medi)

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [77]:
#listooo
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo INT
#     obs_30_cnt_social_circle = float(row['OBS_30_CNT_SOCIAL_CIRCLE']) if pd.notna(row['OBS_30_CNT_SOCIAL_CIRCLE']) else 0
#     def_30_cnt_social_circle = float(row['DEF_30_CNT_SOCIAL_CIRCLE']) if pd.notna(row['DEF_30_CNT_SOCIAL_CIRCLE']) else 0
#     obs_60_cnt_social_circle = float(row['OBS_60_CNT_SOCIAL_CIRCLE']) if pd.notna(row['OBS_60_CNT_SOCIAL_CIRCLE']) else 0
#     def_60_cnt_social_circle = float(row['DEF_60_CNT_SOCIAL_CIRCLE']) if pd.notna(row['DEF_60_CNT_SOCIAL_CIRCLE']) else 0

#     insert_query = '''
#     INSERT INTO CUSTUMER_CUSTOMER_APPLICATION_TRAIN (ID, OBS_30_CNT_SOCIAL_CIRCLE, DEF_30_CNT_SOCIAL_CIRCLE, OBS_60_CNT_SOCIAL_CIRCLE, 
#         DEF_60_CNT_SOCIAL_CIRCLE) VALUES (?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, row['ID'], obs_30_cnt_social_circle, def_30_cnt_social_circle, obs_60_cnt_social_circle, def_60_cnt_social_circle)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

In [120]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validate and convert columns to INT
    
#     flag_document_2 = int(row['FLAG_DOCUMENT_2']) 
#     flag_document_3 = int(row['FLAG_DOCUMENT_3']) 
#     flag_document_4 = int(row['FLAG_DOCUMENT_4']) 
#     flag_document_5 = int(row['FLAG_DOCUMENT_5']) 
#     flag_document_6 = int(row['FLAG_DOCUMENT_6']) 
#     flag_document_7 = int(row['FLAG_DOCUMENT_7']) 
#     flag_document_8 = int(row['FLAG_DOCUMENT_8']) 
#     flag_document_9 = int(row['FLAG_DOCUMENT_9']) 
#     flag_document_10 = int(row['FLAG_DOCUMENT_10']) 
#     flag_document_11 = int(row['FLAG_DOCUMENT_11']) 
#     flag_document_12 = int(row['FLAG_DOCUMENT_12']) 
#     flag_document_13 = int(row['FLAG_DOCUMENT_13']) 
#     flag_document_14 = int(row['FLAG_DOCUMENT_14']) 
#     flag_document_15 = int(row['FLAG_DOCUMENT_15'])
#     flag_document_16 = int(row['FLAG_DOCUMENT_16']) 
#     flag_document_17 = int(row['FLAG_DOCUMENT_17']) 
#     flag_document_18 = int(row['FLAG_DOCUMENT_18']) 
#     flag_document_19 = int(row['FLAG_DOCUMENT_19']) 
#     flag_document_20 = int(row['FLAG_DOCUMENT_20']) 
#     flag_document_21 = int(row['FLAG_DOCUMENT_21']) 

#     # Insert data into the DOCUMENT_APLICATION_TRAIN table
#     insert_query = '''
#     INSERT INTO DOCUMENT_APLICATION_TRAIN (ID, FLAG_DOCUMENT_2, FLAG_DOCUMENT_3, FLAG_DOCUMENT_4, FLAG_DOCUMENT_5, 
#         FLAG_DOCUMENT_6, FLAG_DOCUMENT_7, FLAG_DOCUMENT_8, FLAG_DOCUMENT_9, FLAG_DOCUMENT_10, FLAG_DOCUMENT_11, 
#         FLAG_DOCUMENT_12, FLAG_DOCUMENT_13, FLAG_DOCUMENT_14, FLAG_DOCUMENT_15, FLAG_DOCUMENT_16, FLAG_DOCUMENT_17, 
#         FLAG_DOCUMENT_18, FLAG_DOCUMENT_19, FLAG_DOCUMENT_20, FLAG_DOCUMENT_21) 
#     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, index, flag_document_2, flag_document_3, flag_document_4, flag_document_5, flag_document_6, flag_document_7, 
#                    flag_document_8, flag_document_9, flag_document_10,flag_document_11, flag_document_12, flag_document_13, flag_document_14, 
#                    flag_document_15, flag_document_16, flag_document_17, flag_document_18, flag_document_19, flag_document_20, flag_document_21)

# # Commit the changes
# conn.commit()

# # Close the cursor and the connection
# cursor.close()
# conn.close()

In [132]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT
#     ext_source_1 = float(row['EXT_SOURCE_1']) if pd.notna(row['EXT_SOURCE_1']) else 0.0
#     ext_source_2 = float(row['EXT_SOURCE_2']) if pd.notna(row['EXT_SOURCE_2']) else 0.0
#     ext_source_3 = float(row['EXT_SOURCE_3']) if pd.notna(row['EXT_SOURCE_3']) else 0.0

#     insert_query = '''
#     INSERT INTO EXT_SOURCES_APPLICATION_TRAIN (ID, EXT_SOURCE_1, EXT_SOURCE_2, EXT_SOURCE_3) VALUES (?, ?, ?, ?)
#     '''
#     cursor.execute(insert_query, row['ID'], ext_source_1, ext_source_2, ext_source_3)

# conn.commit()
# # Cerrar el cursor
# cursor.close()

# # Cerrar la conexión
# conn.close()

*BUREAU*

TABLAS

In [127]:
# LISTOO
# create_table_query = '''
# CREATE TABLE BUREAU (
    # SK_ID_BUREAU INT,
    # CREDIT_ACTIVE CHAR(20),
    # CREDIT_CURRENCY	CHAR(20),
    # CNT_CREDIT_PROLONG INT,
    # CREDIT_TYPE	CHAR(50),
    # SK_ID_CURR INT,
    # ID_CREDIT_TIMELINE INT,
    # ID_CREDIT_AMOUNTS INT,
#     FOREIGN KEY (SK_ID_CURR) REFERENCES APPLICATION_TRAIN (SK_ID_CURR),
#     FOREIGN KEY (ID_CREDIT_TIMELINE) REFERENCES CREDIT_TIMELINE_BUREAU (ID),
#     FOREIGN KEY (ID_CREDIT_AMOUNTS) REFERENCES CREDIT_AMOUNTS_BUREAU (ID),
#     CONSTRAINT pk_BUREAU PRIMARY KEY(SK_ID_BUREAU)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [146]:
#listoo
# create_table_query = '''
# CREATE TABLE CREDIT_TIMELINE_BUREAU (	
#     ID INT,
#     DAYS_CREDIT	INT,
#     CREDIT_DAY_OVERDUE INT,
#     DAYS_CREDIT_ENDDATE	FLOAT,
#     DAYS_ENDDATE_FACT FLOAT,
#     DAYS_CREDIT_UPDATE INT,
#     CONSTRAINT pk_CREDIT_TIMELINE_BUREAU PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [153]:
#LISTOOOO
# create_table_query = '''
# CREATE TABLE CREDIT_AMOUNTS_BUREAU (	
#     ID INT,
#     AMT_CREDIT_MAX_OVERDUE FLOAT,
#     AMT_CREDIT_SUM FLOAT,
#     AMT_CREDIT_SUM_DEBT	FLOAT,
#     AMT_CREDIT_SUM_LIMIT FLOAT,
#     AMT_CREDIT_SUM_OVERDUE FLOAT,
#     AMT_ANUALITY FLOAT,
#     CONSTRAINT pk_CREDIT_AMOUNTS_BUREAU PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

Ingresar Datos

In [ ]:
#LISTOOO

# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo adecuado
#     sk_id_bureau = int(row['SK_ID_BUREAU']) if pd.notnull(row['SK_ID_BUREAU']) else 0
#     id_sk_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0

#     # Check if SK_ID_CURR exists in APPLICATION_TRAIN
#     check_app_query = 'SELECT COUNT(*) FROM APPLICATION_TRAIN WHERE SK_ID_CURR = ?'
#     cursor.execute(check_app_query, (id_sk_curr,))
#     count_app = cursor.fetchone()[0]

#     if count_app > 0:  # SK_ID_CURR exists in APPLICATION_TRAIN, proceed with insertion
#         credit_active = str(row['CREDIT_ACTIVE']) if pd.notnull(row['CREDIT_ACTIVE']) else None
#         credit_currency = str(row['CREDIT_CURRENCY']) if pd.notnull(row['CREDIT_CURRENCY']) else None
#         cnt_credit_prolong = int(row['CNT_CREDIT_PROLONG']) if pd.notnull(row['CNT_CREDIT_PROLONG']) else 0
#         credit_type = str(row['CREDIT_TYPE']) if pd.notnull(row['CREDIT_TYPE']) else None
#         id_credit_timeline = int(row['ID_CREDIT_TIMELINE']) if pd.notnull(row['ID_CREDIT_TIMELINE']) else 0
#         id_credit_amounts = int(row['ID_CREDIT_AMOUNTS']) if pd.notnull(row['ID_CREDIT_AMOUNTS'])  else 0

#         # Crear la consulta de inserción
#         insert_query = '''
#         INSERT INTO BUREAU (SK_ID_BUREAU, CREDIT_ACTIVE, CREDIT_CURRENCY, CNT_CREDIT_PROLONG, CREDIT_TYPE, 
#                     SK_ID_CURR, ID_CREDIT_TIMELINE, ID_CREDIT_AMOUNTS) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
#         '''

#         # Ejecutar la consulta de inserción
#         cursor.execute(insert_query, (sk_id_bureau, credit_active, credit_currency, cnt_credit_prolong, credit_type,
#                                       id_sk_curr, id_credit_timeline, id_credit_amounts))
#     else:
#         print(f"SK_ID_CURR {id_sk_curr} does not exist in APPLICATION_TRAIN. Skipping insertion into BUREAU.")

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [147]:
#listooo
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo INT o 0
#     days_credit = int(row['DAYS_CREDIT']) if pd.notnull(row['DAYS_CREDIT']) and isinstance(row['DAYS_CREDIT'], (int, float)) else 0
#     credit_day_overdue = int(row['CREDIT_DAY_OVERDUE']) if pd.notnull(row['CREDIT_DAY_OVERDUE']) and isinstance(row['CREDIT_DAY_OVERDUE'], (int, float)) else 0.0
#     days_credit_enddate = float(row['DAYS_CREDIT_ENDDATE']) if pd.notnull(row['DAYS_CREDIT_ENDDATE'])else 0
#     days_enddate_fact = float(row['DAYS_ENDDATE_FACT']) if pd.notnull(row['DAYS_ENDDATE_FACT']) else 0.0
#     days_credit_update = int(row['DAYS_CREDIT_UPDATE']) if pd.notnull(row['DAYS_CREDIT_UPDATE']) and isinstance(row['DAYS_CREDIT_UPDATE'], (int, float)) else 0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO CREDIT_TIMELINE_BUREAU (ID, DAYS_CREDIT, CREDIT_DAY_OVERDUE, DAYS_CREDIT_ENDDATE, DAYS_ENDDATE_FACT, DAYS_CREDIT_UPDATE)
#     VALUES (?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], days_credit, credit_day_overdue, days_credit_enddate, days_enddate_fact, days_credit_update))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [154]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     amt_credit_max_overdue = float(row['AMT_CREDIT_MAX_OVERDUE']) if pd.notnull(row['AMT_CREDIT_MAX_OVERDUE']) else 0.0
#     amt_credit_sum = float(row['AMT_CREDIT_SUM']) if pd.notnull(row['AMT_CREDIT_SUM']) else 0.0
#     amt_credit_sum_debt = float(row['AMT_CREDIT_SUM_DEBT']) if pd.notnull(row['AMT_CREDIT_SUM_DEBT']) else 0.0
#     amt_credit_sum_limit = float(row['AMT_CREDIT_SUM_LIMIT']) if pd.notnull(row['AMT_CREDIT_SUM_LIMIT']) else 0.0
#     amt_credit_sum_overdue = float(row['AMT_CREDIT_SUM_OVERDUE']) if pd.notnull(row['AMT_CREDIT_SUM_OVERDUE']) else 0.0
#     amt_annuity = float(row['AMT_ANNUITY']) if pd.notnull(row['AMT_ANNUITY']) else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO CREDIT_AMOUNTS_BUREAU (ID, AMT_CREDIT_MAX_OVERDUE, AMT_CREDIT_SUM, AMT_CREDIT_SUM_DEBT, AMT_CREDIT_SUM_LIMIT, AMT_CREDIT_SUM_OVERDUE, AMT_ANUALITY)
#     VALUES (?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], amt_credit_max_overdue, amt_credit_sum, amt_credit_sum_debt, amt_credit_sum_limit, amt_credit_sum_overdue, amt_annuity))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

*BUREAU_BALANCE*

TABLAS

In [14]:
#LISTOOOO
# create_table_query = '''
# CREATE TABLE BUREAU_BALANCE (	
#     ID INT,
#     SK_ID_BUREAU INT,
#     MONTHS_BALANCE INT,
#     STATUS CHAR(1),
#     FOREIGN KEY (SK_ID_BUREAU) REFERENCES BUREAU (SK_ID_BUREAU),
#     CONSTRAINT pk_BUREAU_BALANCE PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

INSERTAR DATOS

In [ ]:
#LISTOOO

# for index, row in df.iterrows():
#     sk_id_bureau = int(row['SK_ID_BUREAU']) if pd.notnull(row['SK_ID_BUREAU']) else 0

#     # Check if SK_ID_BUREAU exists in BUREAU
#     check_bureau_query = 'SELECT COUNT(*) FROM BUREAU WHERE SK_ID_BUREAU = ?'
#     cursor.execute(check_bureau_query, (sk_id_bureau,))
#     count_bureau = cursor.fetchone()[0]

#     if count_bureau > 0:  # SK_ID_BUREAU exists in BUREAU, proceed with insertion
#         id_bureau_balance = int(row['ID']) if pd.notnull(row['ID']) else 0
#         months_balance = int(row['MONTHS_BALANCE']) if pd.notnull(row['MONTHS_BALANCE']) else 0
#         status = str(row['STATUS']) if pd.notnull(row['STATUS']) else 'X'

#         # Create the insertion query for BUREAU_BALANCE
#         insert_bureau_balance_query = '''
#         INSERT INTO BUREAU_BALANCE (ID, SK_ID_BUREAU, MONTHS_BALANCE, STATUS) VALUES (?, ?, ?, ?)
#         '''

#         # Execute the insertion query for BUREAU_BALANCE
#         cursor.execute(insert_bureau_balance_query, (id_bureau_balance, sk_id_bureau, months_balance, status))
#     else:
#         None
#         #print(f"SK_ID_BUREAU {sk_id_bureau} does not exist in BUREAU. Skipping insertion into BUREAU_BALANCE.")

# # Commit changes and close the connection
# conn.commit()
# conn.close()

*PREVIOUS_APPLICATION*

TABLAS

In [28]:
# create_table_query = '''
# CREATE TABLE PREVIOUS_APPLICATION (	
    # SK_ID_PREV INT,
    # NAME_CONTRACT_TYPE NVARCHAR(50),
    # WEEKDAY_APPR_PROCESS_START NVARCHAR(50),
    # HOUR_APPR_PROCESS_START INT,
    # FLAG_LAST_APPL_PER_CONTRACT CHAR(1),
    # NFLAG_LAST_APPL_IN_DAY INT,
    # NAME_CASH_LOAN_PURPOSE CHAR(50),
    # NAME_CONTRACT_STATUS NVARCHAR(50),
    # DAYS_DECISION INT,
    # NAME_PAYMENT_TYPE NVARCHAR(50),
    # CODE_REJECT_REASON CHAR(50),
    # NAME_TYPE_SUITE	NVARCHAR(50),
    # NAME_CLIENT_TYPE NVARCHAR(50),
    # NAME_GOODS_CATEGORY	CHAR(50),
    # NAME_PORTFOLIO CHAR(50),
    # NAME_PRODUCT_TYPE CHAR(20),
    # CHANNEL_TYPE NVARCHAR(50),
    # SELLERPLACE_AREA INT,
    # NAME_SELLER_INDUSTRY NVARCHAR(50),
    # CNT_PAYMENT	FLOAT,
    # NAME_YIELD_GROUP NVARCHAR(50),
    # PRODUCT_COMBINATION	NVARCHAR(50),
    # ID_INTEREST_RATES INT,
    # ID_AMT_PREVIOUS	INT,
    # ID_LOAN_TERMS INT,
    # SK_ID_CURR INT,
#     FOREIGN KEY (ID_INTEREST_RATES) REFERENCES INTEREST_RATES_PREVIOUS_APPLICATION (ID),
#     FOREIGN KEY (ID_AMT_PREVIOUS) REFERENCES AMT_PREVIOUS_APPLICATION (ID),
#     FOREIGN KEY (ID_LOAN_TERMS) REFERENCES LOAN_TERMS_PREVIOUS_APPLICATION (ID),
#     FOREIGN KEY (SK_ID_CURR) REFERENCES APPLICATION_TRAIN (SK_ID_CURR),
#     CONSTRAINT pk_PREVIOUS_APPLICATION PRIMARY KEY(SK_ID_PREV)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [159]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE INTEREST_RATES_PREVIOUS_APPLICATION (	
#     ID INT,
#     RATE_DOWN_PAYMENT FLOAT,
#     RATE_INTEREST_PRIMARY FLOAT,
#     RATE_INTEREST_PRIVILEGED FLOAT,
#     CONSTRAINT pk_INTEREST_RATES_PREVIOUS_APPLICATION PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [164]:
# LISTOOO
# create_table_query = '''
# CREATE TABLE AMT_PREVIOUS_APPLICATION (	
#     ID INT,
#     AMT_ANNUITY	FLOAT,
#     AMT_APPLICATION	FLOAT,
#     AMT_CREDIT FLOAT,
#     AMT_DOWN_PAYMENT FLOAT,
#     AMT_GOODS_PRICE	FLOAT,
#     CONSTRAINT pk_AMT_PREVIOUS_APPLICATION PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [ ]:
#listooo
# create_table_query = '''
# CREATE TABLE LOAN_TERMS_PREVIOUS_APPLICATION (	
#     ID INT,
#     DAYS_FIRST_DRAWING FLOAT,
#     DAYS_FIRST_DUE FLOAT,
#     DAYS_LAST_DUE_1ST_VERSION FLOAT,
#     DAYS_LAST_DUE FLOAT,
#     DAYS_TERMINATION FLOAT,
#     NFLAG_INSURED_ON_APPROVAL FLOAT,
#     CONSTRAINT pk_LOAN_TERMS_PREVIOUS_APPLICATION PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [29]:

# for index, row in df.iterrows():
#     sk_id_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0

#     # Check if SK_ID_CURR exists in APPLICATION_TRAIN
#     check_application_query = 'SELECT COUNT(*) FROM APPLICATION_TRAIN WHERE SK_ID_CURR = ?'
#     cursor.execute(check_application_query, (sk_id_curr,))
#     count_application = cursor.fetchone()[0]

#     if count_application > 0:  # SK_ID_BUREAU exists in BUREAU, proceed with insertion

#         sk_id_prev = int(row['SK_ID_PREV']) if pd.notnull(row['SK_ID_PREV']) else 0
#         name_contract_type = row['NAME_CONTRACT_TYPE'] if pd.notnull(row['NAME_CONTRACT_TYPE']) else None
#         weekday_appr_process_start = row['WEEKDAY_APPR_PROCESS_START'] if pd.notnull(row['WEEKDAY_APPR_PROCESS_START']) else None
#         hour_appr_process_start = int(row['HOUR_APPR_PROCESS_START']) if pd.notnull(row['HOUR_APPR_PROCESS_START']) else 0
#         flag_last_appl_per_contract = row['FLAG_LAST_APPL_PER_CONTRACT'] if pd.notnull(row['FLAG_LAST_APPL_PER_CONTRACT']) else 'Y'
#         nflag_last_appl_in_day = int(row['NFLAG_LAST_APPL_IN_DAY']) if pd.notnull(row['NFLAG_LAST_APPL_IN_DAY']) else 0
#         name_cash_loan_purpose = row['NAME_CASH_LOAN_PURPOSE'] if pd.notnull(row['NAME_CASH_LOAN_PURPOSE']) else None
#         name_contract_status = row['NAME_CONTRACT_STATUS'] if pd.notnull(row['NAME_CONTRACT_STATUS']) else None
#         days_decision = int(row['DAYS_DECISION']) if pd.notnull(row['DAYS_DECISION']) else 0
#         name_payment_type = row['NAME_PAYMENT_TYPE'] if pd.notnull(row['NAME_PAYMENT_TYPE']) else None
#         code_reject_reason = row['CODE_REJECT_REASON'] if pd.notnull(row['CODE_REJECT_REASON']) else None
#         name_type_suite = row['NAME_TYPE_SUITE'] if pd.notnull(row['NAME_TYPE_SUITE']) else None
#         name_client_type = row['NAME_CLIENT_TYPE'] if pd.notnull(row['NAME_CLIENT_TYPE']) else None
#         name_goods_category = row['NAME_GOODS_CATEGORY'] if pd.notnull(row['NAME_GOODS_CATEGORY']) else None
#         name_portfolio = row['NAME_PORTFOLIO'] if pd.notnull(row['NAME_PORTFOLIO']) else None
#         name_product_type = row['NAME_PRODUCT_TYPE'] if pd.notnull(row['NAME_PRODUCT_TYPE']) else None
#         channel_type = row['CHANNEL_TYPE'] if pd.notnull(row['CHANNEL_TYPE']) else None
#         sellerplace_area = int(row['SELLERPLACE_AREA']) if pd.notnull(row['SELLERPLACE_AREA']) else 0
#         name_seller_industry = row['NAME_SELLER_INDUSTRY'] if pd.notnull(row['NAME_SELLER_INDUSTRY']) else None
#         cnt_payment = int(float(row['CNT_PAYMENT'])) if pd.notnull(row['CNT_PAYMENT']) else 0.0
#         name_yield_group = row['NAME_YIELD_GROUP'] if pd.notnull(row['NAME_YIELD_GROUP']) else None
#         product_combination = row['PRODUCT_COMBINATION'] if pd.notnull(row['PRODUCT_COMBINATION']) else None
#         id_interest_rates = int(row['ID_INTEREST_RATES']) if pd.notnull(row['ID_INTEREST_RATES']) else 0
#         id_amt_previous = int(row['ID_AMT_PREVIOUS']) if pd.notnull(row['ID_AMT_PREVIOUS']) else 0
#         id_loan_terms = int(row['ID_LOAN_TERMS']) if pd.notnull(row['ID_LOAN_TERMS']) else 0
        

#         # Create the insertion query for PREVIOUS_APPLICATION
#         insert_previous_application_query = '''
#         INSERT INTO PREVIOUS_APPLICATION (SK_ID_PREV, NAME_CONTRACT_TYPE, WEEKDAY_APPR_PROCESS_START, HOUR_APPR_PROCESS_START, FLAG_LAST_APPL_PER_CONTRACT, 
#         NFLAG_LAST_APPL_IN_DAY, NAME_CASH_LOAN_PURPOSE, NAME_CONTRACT_STATUS, DAYS_DECISION, NAME_PAYMENT_TYPE, CODE_REJECT_REASON, NAME_TYPE_SUITE,
#         NAME_CLIENT_TYPE, NAME_GOODS_CATEGORY, NAME_PORTFOLIO, NAME_PRODUCT_TYPE, CHANNEL_TYPE, SELLERPLACE_AREA, NAME_SELLER_INDUSTRY, CNT_PAYMENT, NAME_YIELD_GROUP,
#         PRODUCT_COMBINATION, ID_INTEREST_RATES, ID_AMT_PREVIOUS, ID_LOAN_TERMS, SK_ID_CURR) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#         '''

#         # Execute the insertion query for PREVIOUS_APPLICATION
#         cursor.execute(insert_previous_application_query, sk_id_prev, name_contract_type, weekday_appr_process_start,
#         hour_appr_process_start, flag_last_appl_per_contract, nflag_last_appl_in_day, name_cash_loan_purpose,
#         name_contract_status, days_decision, name_payment_type, code_reject_reason, name_type_suite, name_client_type,
#         name_goods_category, name_portfolio, name_product_type, channel_type, sellerplace_area, name_seller_industry,
#         cnt_payment, name_yield_group, product_combination, id_interest_rates, id_amt_previous, id_loan_terms, sk_id_curr)

#     else:
#        None

# # Commit changes and close the connection
# conn.commit()
# conn.close()

In [160]:
#LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     rate_down_payment = float(row['RATE_DOWN_PAYMENT']) if pd.notnull(row['RATE_DOWN_PAYMENT']) else 0.0
#     rate_interest_primary = float(row['RATE_INTEREST_PRIMARY']) if pd.notnull(row['RATE_INTEREST_PRIMARY']) else 0.0
#     rate_interest_privileged = float(row['RATE_INTEREST_PRIVILEGED']) if pd.notnull(row['RATE_INTEREST_PRIVILEGED']) else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO INTEREST_RATES_PREVIOUS_APPLICATION (ID, RATE_DOWN_PAYMENT, RATE_INTEREST_PRIMARY, RATE_INTEREST_PRIVILEGED)
#     VALUES (?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], rate_down_payment, rate_interest_primary, rate_interest_privileged))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [165]:
#LISTOOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     amt_annuity = float(row['AMT_ANNUITY']) if pd.notnull(row['AMT_ANNUITY']) else 0.0
#     amt_application = float(row['AMT_APPLICATION']) if pd.notnull(row['AMT_APPLICATION']) else 0.0
#     amt_credit = float(row['AMT_CREDIT']) if pd.notnull(row['AMT_CREDIT']) else 0.0
#     amt_down_payment = float(row['AMT_DOWN_PAYMENT']) if pd.notnull(row['AMT_DOWN_PAYMENT']) else 0.0
#     amt_goods_price = float(row['AMT_GOODS_PRICE']) if pd.notnull(row['AMT_GOODS_PRICE'])  else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO AMT_PREVIOUS_APPLICATION (ID, AMT_ANNUITY, AMT_APPLICATION, AMT_CREDIT, AMT_DOWN_PAYMENT, AMT_GOODS_PRICE)
#     VALUES (?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], amt_annuity, amt_application, amt_credit, amt_down_payment, amt_goods_price))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [170]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     days_first_drawing = float(row['DAYS_FIRST_DRAWING']) if pd.notnull(row['DAYS_FIRST_DRAWING']) else 0.0
#     days_first_due = float(row['DAYS_FIRST_DUE']) if pd.notnull(row['DAYS_FIRST_DUE']) else 0.0
#     days_last_due_1st_version = float(row['DAYS_LAST_DUE_1ST_VERSION']) if pd.notnull(row['DAYS_LAST_DUE_1ST_VERSION']) else 0.0
#     days_last_due = float(row['DAYS_LAST_DUE']) if pd.notnull(row['DAYS_LAST_DUE']) else 0.0
#     days_termination = float(row['DAYS_TERMINATION']) if pd.notnull(row['DAYS_TERMINATION']) else 0.0
#     nflag_insured_on_approval = float(row['NFLAG_INSURED_ON_APPROVAL']) if pd.notnull(row['NFLAG_INSURED_ON_APPROVAL']) else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO LOAN_TERMS_PREVIOUS_APPLICATION (ID, DAYS_FIRST_DRAWING, DAYS_FIRST_DUE, DAYS_LAST_DUE_1ST_VERSION, DAYS_LAST_DUE, DAYS_TERMINATION, NFLAG_INSURED_ON_APPROVAL)
#     VALUES (?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], days_first_drawing, days_first_due, days_last_due_1st_version, days_last_due, days_termination, nflag_insured_on_approval))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

*CREDIT CARD BALANCED*

TABLAS

In [21]:
# create_table_query = '''
# CREATE TABLE CREDIT_CARD_BALANCED (	
#     SK_ID_CURR INT,
#     MONTHS_BALANCE INT,
#     AMT_BALANCE	FLOAT,
#     AMT_CREDIT_LIMIT_ACTUAL	INT,
#     AMT_INST_MIN_REGULARITY	FLOAT,
#     AMT_PAYMENT_CURRENT	FLOAT,
#     AMT_PAYMENT_TOTAL_CURRENT FLOAT,
#     AMT_RECEIVABLE_PRINCIPAL FLOAT,
#     AMT_RECIVABLE FLOAT,
#     AMT_TOTAL_RECEIVABLE FLOAT,
#     CNT_INSTALMENT_MATURE_CUM FLOAT,
#     NAME_CONTRACT_STATUS NVARCHAR(50),
#     SK_DPD INT,
#     SK_DPD_DEF INT,
#     ID_CREDIT_CARD_DRAWINGS	INT,
#     SK_ID_PREV INT,
#     FOREIGN KEY (ID_CREDIT_CARD_DRAWINGS) REFERENCES CREDIT_CARD_DRAWINGS (ID),
#     FOREIGN KEY (SK_ID_PREV) REFERENCES PREVIOUS_APPLICATION (SK_ID_PREV),
#     CONSTRAINT pk_CREDIT_CARD_BALANCED PRIMARY KEY(SK_ID_CURR)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

In [174]:
#LISTOOO
# create_table_query = '''
# CREATE TABLE CREDIT_CARD_DRAWINGS (	
#     ID INT,
#     AMT_DRAWINGS_ATM_CURRENT FLOAT,
#     AMT_DRAWINGS_CURRENT FLOAT,
#     AMT_DRAWINGS_OTHER_CURRENT FLOAT,
#     AMT_DRAWINGS_POS_CURRENT FLOAT,
#     CNT_DRAWINGS_ATM_CURRENT FLOAT,
#     CNT_DRAWINGS_CURRENT FLOAT,
#     CNT_DRAWINGS_OTHER_CURRENT FLOAT,
#     CNT_DRAWINGS_POS_CURRENT FLOAT,
#     CONSTRAINT pk_CREDIT_CARD_DRAWINGS PRIMARY KEY(ID)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

INSERTAR DATOS

In [22]:

# Create a set to keep track of processed SK_ID_CURR
# processed_sk_ids = set()

# for index, row in df.iterrows():
#     sk_id_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0
    
#     # Check if SK_ID_CURR has been processed
#     if sk_id_curr in processed_sk_ids:
#         #print(f"SK_ID_CURR {sk_id_curr} already processed. Skipping insertion.")
#         continue

#     # Mark SK_ID_CURR as processed
#     processed_sk_ids.add(sk_id_curr)

#     months_balance = int(row['MONTHS_BALANCE']) if pd.notnull(row['MONTHS_BALANCE']) else 0
#     amt_balance = float(row['AMT_BALANCE']) if pd.notnull(row['AMT_BALANCE']) else 0.0
#     amt_credit_limit_actual = int(row['AMT_CREDIT_LIMIT_ACTUAL']) if pd.notnull(row['AMT_CREDIT_LIMIT_ACTUAL']) else 0
#     amt_inst_min_regularity = float(row['AMT_INST_MIN_REGULARITY']) if pd.notnull(row['AMT_INST_MIN_REGULARITY']) else 0.0
#     amt_payment_current = float(row['AMT_PAYMENT_CURRENT']) if pd.notnull(row['AMT_PAYMENT_CURRENT']) else 0.0
#     amt_payment_total_current = float(row['AMT_PAYMENT_TOTAL_CURRENT']) if pd.notnull(row['AMT_PAYMENT_TOTAL_CURRENT']) else 0.0
#     amt_receivable_principal = float(row['AMT_RECEIVABLE_PRINCIPAL']) if pd.notnull(row['AMT_RECEIVABLE_PRINCIPAL']) else 0.0
#     amt_recivable = float(row['AMT_RECIVABLE']) if pd.notnull(row['AMT_RECIVABLE']) else 0.0
#     amt_total_receivable = float(row['AMT_TOTAL_RECEIVABLE']) if pd.notnull(row['AMT_TOTAL_RECEIVABLE']) else 0.0
#     cnt_instalment_mature_cum = float(row['CNT_INSTALMENT_MATURE_CUM']) if pd.notnull(row['CNT_INSTALMENT_MATURE_CUM']) else 0.0
#     name_contract_status = str(row['NAME_CONTRACT_STATUS']) if pd.notnull(row['NAME_CONTRACT_STATUS']) else None
#     sk_dpd = int(row['SK_DPD']) if pd.notnull(row['SK_DPD']) else 0
#     sk_dpd_def = int(row['SK_DPD_DEF']) if pd.notnull(row['SK_DPD_DEF']) else 0
#     id_credit_card_drawings = int(row['ID_CREDIT_CARD_DRAWINGS']) if pd.notnull(row['ID_CREDIT_CARD_DRAWINGS']) else 0
#     sk_id_prev = int(row['SK_ID_PREV']) if pd.notnull(row['SK_ID_PREV']) else 0

#     # Check if SK_ID_PREV exists in PREVIOUS_APPLICATION
#     check_prev_app_query = 'SELECT COUNT(*) FROM PREVIOUS_APPLICATION WHERE SK_ID_PREV = ?'
#     cursor.execute(check_prev_app_query, (sk_id_prev,))
#     count_prev_app = cursor.fetchone()[0]

#     if count_prev_app > 0:  # SK_ID_PREV exists in PREVIOUS_APPLICATION, proceed with insertion
#         # Crear la consulta de inserción
#         insert_query = '''
#         INSERT INTO CREDIT_CARD_BALANCED (SK_ID_CURR, MONTHS_BALANCE, AMT_BALANCE, AMT_CREDIT_LIMIT_ACTUAL, AMT_INST_MIN_REGULARITY, 
#         AMT_PAYMENT_CURRENT, AMT_PAYMENT_TOTAL_CURRENT, AMT_RECEIVABLE_PRINCIPAL, AMT_RECIVABLE, AMT_TOTAL_RECEIVABLE, 
#         CNT_INSTALMENT_MATURE_CUM, NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, ID_CREDIT_CARD_DRAWINGS, SK_ID_PREV)
#         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
#         '''

#         # Ejecutar la consulta de inserción
#         cursor.execute(insert_query, (sk_id_curr, months_balance, amt_balance, amt_credit_limit_actual, amt_inst_min_regularity, 
#                                       amt_payment_current, amt_payment_total_current, amt_receivable_principal,
#                                       amt_recivable, amt_total_receivable, cnt_instalment_mature_cum,
#                                       name_contract_status, sk_dpd, sk_dpd_def, id_credit_card_drawings, sk_id_prev))
#     else:
#         None

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

In [175]:
#LISTOOO
# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo FLOAT o 0
#     amt_drawings_atm_current = float(row['AMT_DRAWINGS_ATM_CURRENT']) if pd.notnull(row['AMT_DRAWINGS_ATM_CURRENT']) else 0.0
#     amt_drawings_current = float(row['AMT_DRAWINGS_CURRENT']) if pd.notnull(row['AMT_DRAWINGS_CURRENT']) else 0.0
#     amt_drawings_other_current = float(row['AMT_DRAWINGS_OTHER_CURRENT']) if pd.notnull(row['AMT_DRAWINGS_OTHER_CURRENT']) else 0.0
#     amt_drawings_pos_current = float(row['AMT_DRAWINGS_POS_CURRENT']) if pd.notnull(row['AMT_DRAWINGS_POS_CURRENT']) else 0.0
#     cnt_drawings_atm_current = float(row['CNT_DRAWINGS_ATM_CURRENT']) if pd.notnull(row['CNT_DRAWINGS_ATM_CURRENT'])  else 0.0
#     cnt_drawings_current = float(row['CNT_DRAWINGS_CURRENT']) if pd.notnull(row['CNT_DRAWINGS_CURRENT']) else 0.0
#     cnt_drawings_other_current = float(row['CNT_DRAWINGS_OTHER_CURRENT']) if pd.notnull(row['CNT_DRAWINGS_OTHER_CURRENT']) else 0.0
#     cnt_drawings_pos_current = float(row['CNT_DRAWINGS_POS_CURRENT']) if pd.notnull(row['CNT_DRAWINGS_POS_CURRENT']) else 0.0

#     # Crear la consulta de inserción
#     insert_query = '''
#     INSERT INTO CREDIT_CARD_DRAWINGS (ID, AMT_DRAWINGS_ATM_CURRENT, AMT_DRAWINGS_CURRENT, AMT_DRAWINGS_OTHER_CURRENT, AMT_DRAWINGS_POS_CURRENT,
#                                       CNT_DRAWINGS_ATM_CURRENT, CNT_DRAWINGS_CURRENT, CNT_DRAWINGS_OTHER_CURRENT, CNT_DRAWINGS_POS_CURRENT)
#     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
#     '''

#     # Ejecutar la consulta de inserción
#     cursor.execute(insert_query, (row['ID'], amt_drawings_atm_current, amt_drawings_current, amt_drawings_other_current, amt_drawings_pos_current,
#                                   cnt_drawings_atm_current, cnt_drawings_current, cnt_drawings_other_current, cnt_drawings_pos_current))

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

*INSTALLMENTS_PAYMENTS*

TABLAS

In [6]:
# create_table_query = '''
# CREATE TABLE INSTALLMENTS_PAYMENT (	
#     SK_ID_CURR INT,
#     NUM_INSTALMENT_VERSION FLOAT,
#     NUM_INSTALMENT_NUMBER INT,
#     DAYS_INSTALMENT	FLOAT,
#     DAYS_ENTRY_PAYMENT FLOAT,
#     AMT_INSTALMENT FLOAT,
#     AMT_PAYMENT	FLOAT,
#     SK_ID_PREV INT,
#     FOREIGN KEY (SK_ID_PREV) REFERENCES PREVIOUS_APPLICATION (SK_ID_PREV),
#     CONSTRAINT pk_INSTALLMENTS_PAYMENT PRIMARY KEY(SK_ID_CURR)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

INSERTAR DATOS

In [7]:

# Create a set to keep track of processed SK_ID_CURR
# processed_sk_ids = set()

# for index, row in df.iterrows():
#     # Validar y convertir las columnas a tipo adecuado
#     sk_id_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0
#     num_instalment_version = float(row['NUM_INSTALMENT_VERSION']) if pd.notnull(row['NUM_INSTALMENT_VERSION']) else 0.0
#     num_instalment_number = int(row['NUM_INSTALMENT_NUMBER']) if pd.notnull(row['NUM_INSTALMENT_NUMBER']) else 0
#     days_instalment = float(row['DAYS_INSTALMENT']) if pd.notnull(row['DAYS_INSTALMENT']) else 0.0
#     days_entry_payment = float(row['DAYS_ENTRY_PAYMENT']) if pd.notnull(row['DAYS_ENTRY_PAYMENT']) else 0.0
#     amt_instalment = float(row['AMT_INSTALMENT']) if pd.notnull(row['AMT_INSTALMENT']) else 0.0
#     amt_payment = float(row['AMT_PAYMENT']) if pd.notnull(row['AMT_PAYMENT']) else 0.0
#     sk_id_prev = int(row['SK_ID_PREV']) if pd.notnull(row['SK_ID_PREV']) else 0

#     # Check if SK_ID_CURR has been processed
#     if sk_id_curr in processed_sk_ids:
#         #print(f"SK_ID_CURR {sk_id_curr} already processed. Skipping insertion.")
#         continue

#     # Mark SK_ID_CURR as processed
#     processed_sk_ids.add(sk_id_curr)

#     # Check if SK_ID_PREV exists in PREVIOUS_APPLICATION
#     check_prev_app_query = 'SELECT COUNT(*) FROM PREVIOUS_APPLICATION WHERE SK_ID_PREV = ?'
#     cursor.execute(check_prev_app_query, (sk_id_prev,))
#     count_prev_app = cursor.fetchone()[0]

#     if count_prev_app > 0:  # SK_ID_PREV exists in PREVIOUS_APPLICATION, proceed with insertion
#         # Crear la consulta de inserción
#         insert_query = '''
#         INSERT INTO INSTALLMENTS_PAYMENT (SK_ID_CURR, NUM_INSTALMENT_VERSION, NUM_INSTALMENT_NUMBER, DAYS_INSTALMENT,
#         DAYS_ENTRY_PAYMENT, AMT_INSTALMENT, AMT_PAYMENT, SK_ID_PREV) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
#         '''

#         # Ejecutar la consulta de inserción
#         cursor.execute(insert_query, (sk_id_curr, num_instalment_version, num_instalment_number, days_instalment,
#                                       days_entry_payment, amt_instalment, amt_payment, sk_id_prev))
#     else:
#         None

# # Confirmar los cambios y cerrar la conexión
# conn.commit()
# conn.close()

*POS_CASH_BALANCE*

TABLAS

In [25]:
# create_table_query = '''
# CREATE TABLE POS_CASH_BALANCE (	
#     SK_ID_PREV INT,
#     MONTHS_BALANCE INT,
#     CNT_INSTALMENT FLOAT,
#     CNT_INSTALMENT_FUTURE FLOAT,
#     NAME_CONTRACT_STATUS NVARCHAR(50),
#     SK_DPD INT,
#     SK_DPD_DEF INT,
#     SK_ID_CURR INT,
#     FOREIGN KEY (SK_ID_PREV) REFERENCES PREVIOUS_APPLICATION (SK_ID_PREV),
#     CONSTRAINT pk_POS_CASH_BALANCE PRIMARY KEY(SK_ID_CURR)
# )
# '''
# cursor.execute(create_table_query)
# conn.commit()

INSERTAR DATOS

In [26]:


# Create a set to keep track of processed SK_ID_CURR
# processed_sk_ids = set()

# for index, row in df.iterrows():
#     sk_id_prev = int(row['SK_ID_PREV']) if pd.notnull(row['SK_ID_PREV']) else 0
#     months_balance = int(row['MONTHS_BALANCE']) if pd.notnull(row['MONTHS_BALANCE']) else 0
#     cnt_instalment = float(row['CNT_INSTALMENT']) if pd.notnull(row['CNT_INSTALMENT']) else 0.0
#     cnt_instalment_future = float(row['CNT_INSTALMENT_FUTURE']) if pd.notnull(row['CNT_INSTALMENT_FUTURE']) else 0.0
#     name_contract_status = str(row['NAME_CONTRACT_STATUS']) if pd.notnull(row['NAME_CONTRACT_STATUS']) else None
#     sk_dpd = int(row['SK_DPD']) if pd.notnull(row['SK_DPD']) else 0
#     sk_dpd_def = int(row['SK_DPD_DEF']) if pd.notnull(row['SK_DPD_DEF']) else 0
#     sk_id_curr = int(row['SK_ID_CURR']) if pd.notnull(row['SK_ID_CURR']) else 0

#     # Check if SK_ID_CURR has been processed
#     if sk_id_curr in processed_sk_ids:
#         #print(f"SK_ID_CURR {sk_id_curr} already processed. Skipping insertion.")
#         continue

#     # Mark SK_ID_CURR as processed
#     processed_sk_ids.add(sk_id_curr)

#     # Check if SK_ID_PREV exists in PREVIOUS_APPLICATION
#     check_prev_app_query = 'SELECT COUNT(*) FROM PREVIOUS_APPLICATION WHERE SK_ID_PREV = ?'
#     cursor.execute(check_prev_app_query, (sk_id_prev,))
#     count_prev_app = cursor.fetchone()[0]

#     if count_prev_app > 0:  # SK_ID_CURR exists in PREVIOUS_APPLICATION, proceed with insertion
#         # Create the insertion query for POS_CASH_BALANCE
#         insert_pos_cash_balance_query = '''
#         INSERT INTO POS_CASH_BALANCE (SK_ID_PREV, MONTHS_BALANCE, CNT_INSTALMENT, CNT_INSTALMENT_FUTURE,
#         NAME_CONTRACT_STATUS, SK_DPD, SK_DPD_DEF, SK_ID_CURR)
#         VALUES (?, ?, ?, ?, ?, ?, ?, ?)
#         '''

#         # Execute the insertion query for POS_CASH_BALANCE
#         cursor.execute(insert_pos_cash_balance_query, (sk_id_prev, months_balance, cnt_instalment,
#                                                       cnt_instalment_future, name_contract_status, sk_dpd,
#                                                       sk_dpd_def, sk_id_curr))
#     else:
#         None
# # Commit changes and close the connection
# conn.commit()
# conn.close()